@WorldCities.Server_HostAddress = https://localhost:40443

###
GET https://localhost:40443/api/cities/1
Accept: application/json

###
GET https://localhost:40443/api/countries/1
Accept: application/json
